name: qora_flutter
description: >-
  A Flutter implementation for Qora, bringing powerful async state management, 
  automatic caching, and offline-first capabilities to the widget tree.
version: 0.7.0
homepage: https://github.com/meragix/qora
repository: https://github.com/meragix/qora/tree/main/packages/flutter
issue_tracker: https://github.com/meragix/qora/issues
documentation: https://qora.meragix.dev

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  qora: ^0.6.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0

# Configuration pour que le package soit considéré comme un package Flutter
flutter: {}
